// ============================================================================
// RiskShield AI — AI Analyst Orchestrator
// ----------------------------------------------------------------------------
// This is the ONLY place in the app that decides whether to call a real LLM
// or use the deterministic fallback. Every caller (API routes) goes through
// here, so the "graceful fallback" behavior is guaranteed in one spot rather
// than re-implemented per-route.
// ============================================================================

import { getAIProvider } from "./provider";
import { buildFallbackInvestigationSummary, buildFallbackAnalystAnswer } from "./fallback";
import type { AIInvestigationSummary, AnalystAnswer, TransactionAIContext } from "./types";

function buildInvestigationSystemPrompt(): string {
  return [
    "You are RiskShield Analyst, an assistant that helps human payment-risk analysts understand transactions.",
    "You will be given structured, already-calculated evidence about ONE transaction: its risk score, risk level, and a list of specific risk factors with point impacts.",
    "Rules you MUST follow:",
    "1. Use ONLY the supplied evidence. Do not invent transaction details, amounts, dates, or behaviors that are not present in the input.",
    "2. Clearly separate OBSERVED facts (directly from the data) from your INFERENCE (your interpretation of what the pattern might mean). Never present an inference as a fact.",
    "3. If the evidence is insufficient to explain the score, say so explicitly rather than guessing.",
    "4. The final decision belongs to a human analyst. Frame your output as a recommendation, never as a final decision.",
    "5. Respond with ONLY a JSON object (no markdown, no prose outside the JSON) matching exactly this shape:",
    `{"riskSummary": string, "whyItIsSuspicious": string[], "evidence": string[], "recommendedAction": "approve"|"monitor"|"verify"|"manual_review"|"block", "actionRationale": string, "confidence": "low"|"medium"|"high"}`,
  ].join("\n");
}

function buildInvestigationUserPrompt(ctx: TransactionAIContext): string {
  return JSON.stringify(
    {
      transaction: {
        ref: ctx.transactionRef,
        amount: ctx.amount,
        currency: ctx.currency,
        merchant: ctx.merchantName,
        paymentMethod: ctx.paymentMethod,
        timestamp: ctx.timestamp,
      },
      customer: {
        ref: ctx.customerRef,
        accountAgeDays: ctx.accountAgeDays,
        historicalAvgAmount: ctx.historicalAvgAmount,
      },
      behavioral_features: {
        location: ctx.location,
        previousLocation: ctx.previousLocation ?? null,
        isNewDevice: ctx.isNewDevice,
        isNewLocation: ctx.isNewLocation,
        failedAttempts: ctx.failedAttempts,
        transactionsLast10Min: ctx.transactionsLast10Min,
        transactionsLast24h: ctx.transactionsLast24h,
      },
      risk_assessment: {
        ruleScore: ctx.ruleScore,
        mlAnomalyScore: ctx.mlAnomalyScore,
        finalScore: ctx.finalScore,
        riskLevel: ctx.riskLevel,
        riskFactors: ctx.riskFactors,
        systemRecommendedAction: ctx.recommendedAction,
        systemActionReason: ctx.actionReason,
      },
    },
    null,
    2
  );
}

export async function analyzeTransactionWithAI(
  ctx: TransactionAIContext
): Promise<AIInvestigationSummary> {
  const provider = getAIProvider();
  if (!provider.isConfigured) {
    return buildFallbackInvestigationSummary(ctx);
  }

  try {
    const raw = await provider.generateJSON(
      buildInvestigationSystemPrompt(),
      buildInvestigationUserPrompt(ctx)
    );
    const cleaned = raw.trim().replace(/^```json\s*/i, "").replace(/```$/, "");
    const parsed = JSON.parse(cleaned);

    if (
      !parsed.riskSummary ||
      !Array.isArray(parsed.whyItIsSuspicious) ||
      !Array.isArray(parsed.evidence) ||
      !parsed.recommendedAction
    ) {
      throw new Error("AI response did not match the expected shape");
    }

    return {
      riskSummary: String(parsed.riskSummary),
      whyItIsSuspicious: parsed.whyItIsSuspicious.map(String),
      evidence: parsed.evidence.map(String),
      recommendedAction: parsed.recommendedAction,
      actionRationale: String(parsed.actionRationale ?? ctx.actionReason),
      confidence: ["low", "medium", "high"].includes(parsed.confidence) ? parsed.confidence : "medium",
      source: "llm",
      disclaimer:
        "This analysis was generated by an AI model from the structured evidence above. It is a recommendation only — the final decision belongs to a human reviewer.",
    };
  } catch (err) {
    console.warn(
      "[ai/analyst] Falling back to deterministic template:",
      err instanceof Error ? err.message : err
    );
    return buildFallbackInvestigationSummary(ctx);
  }
}

export async function answerAnalystQuestion(
  question: string,
  structuredContextSummary: string
): Promise<AnalystAnswer> {
  const provider = getAIProvider();
  if (!provider.isConfigured) {
    return buildFallbackAnalystAnswer(question, structuredContextSummary);
  }

  try {
    const systemPrompt = [
      "You are RiskShield Analyst, an assistant embedded in a payment risk operations dashboard.",
      "A human risk analyst is asking you a question. You are given a structured summary of the relevant application data below the question.",
      "Rules: Use ONLY the supplied data. If the data doesn't answer the question, say so plainly instead of guessing.",
      "Keep answers concise (a few sentences, or a short list) and written for a professional risk analyst, not a general audience.",
      "Respond with plain text only (no JSON, no markdown headers).",
    ].join("\n");
    const userPrompt = `Analyst question: ${question}\n\nAvailable data:\n${structuredContextSummary}`;

    const raw = await provider.generateJSON(systemPrompt, userPrompt);
    // Some providers (OpenAI JSON mode) always return JSON; try to unwrap common shapes gracefully.
    let answer = raw.trim();
    try {
      const maybeJson = JSON.parse(answer);
      if (typeof maybeJson === "string") answer = maybeJson;
      else if (typeof maybeJson.answer === "string") answer = maybeJson.answer;
    } catch {
      // not JSON, that's fine — plain text is what we asked for
    }

    return { answer, source: "llm" };
  } catch (err) {
    console.warn(
      "[ai/analyst] Falling back to deterministic template for Q&A:",
      err instanceof Error ? err.message : err
    );
    return buildFallbackAnalystAnswer(question, structuredContextSummary);
  }
}
