// ============================================================================
// RiskShield AI — Rule-Based Scoring Engine
// ----------------------------------------------------------------------------
// This is the deterministic, explainable heart of the platform. Every point
// added to a score comes from a specific `if` statement below, tied to a
// real field on the transaction. Nothing here is random, and nothing here
// is generated by an LLM — that is what makes it explainable and auditable.
//
// Each function returns a RiskFactorResult describing *why* it fired. If a
// rule finds nothing risky, it contributes 0 points and produces no factor
// (so the explanation list only ever shows what actually mattered).
// ============================================================================

import { RULE_THRESHOLDS, CATEGORY_MAX_POINTS } from "./config";
import type {
  RawTransactionInput,
  RiskFactorResult,
  RuleScoreBreakdown,
} from "./types";

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function severityFor(points: number, maxPoints: number): "info" | "low" | "medium" | "high" {
  const ratio = points / maxPoints;
  if (ratio >= 0.75) return "high";
  if (ratio >= 0.4) return "medium";
  if (ratio > 0) return "low";
  return "info";
}

// ---------------------------------------------------------------------------
// 1. Amount anomaly — how unusual is this amount for this customer?
// ---------------------------------------------------------------------------
export function scoreAmountAnomaly(input: RawTransactionInput): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.amount;
  const max = CATEGORY_MAX_POINTS.amount_anomaly;

  if (!input.historicalAvgAmount || input.historicalAvgAmount <= 0) {
    // Brand new customer — we can't compute a deviation, so we apply a small,
    // clearly-labelled flat risk only if the amount itself is large.
    if (input.amount >= t.noHistoryMinAmount) {
      return {
        category: "amount_anomaly",
        description: `No transaction history exists for this customer, and the amount (₹${input.amount.toLocaleString()}) is high enough to warrant caution`,
        impact: t.noHistoryFlatPoints,
        severity: severityFor(t.noHistoryFlatPoints, max),
      };
    }
    return null;
  }

  const ratio = input.amount / input.historicalAvgAmount;
  if (ratio <= t.safeRatio) return null;

  let points: number;
  if (ratio <= t.moderateRatio) {
    points = ((ratio - t.safeRatio) / (t.moderateRatio - t.safeRatio)) * 8;
  } else if (ratio <= t.highRatio) {
    points = 8 + ((ratio - t.moderateRatio) / (t.highRatio - t.moderateRatio)) * 7;
  } else if (ratio <= t.severeRatio) {
    points = 15 + ((ratio - t.highRatio) / (t.severeRatio - t.highRatio)) * 4;
  } else {
    points = max;
  }
  points = clamp(Math.round(points), 0, max);
  if (points <= 0) return null;

  return {
    category: "amount_anomaly",
    description: `Transaction amount is ${ratio.toFixed(1)}x higher than the customer's normal average (₹${Math.round(
      input.historicalAvgAmount
    ).toLocaleString()})`,
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// 2. Velocity risk — too many transactions, too fast
// ---------------------------------------------------------------------------
export function scoreVelocityRisk(input: RawTransactionInput): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.velocity;
  const max = CATEGORY_MAX_POINTS.velocity_risk;

  const tenMinExtra = Math.max(0, input.transactionsLast10Min - 1);
  const tenMinPoints = clamp(tenMinExtra * t.tenMinPointsPerExtraTxn, 0, t.tenMinCap);

  let dayPoints = 0;
  if (input.transactionsLast24h >= t.dayCountHighThreshold) dayPoints = t.dayHighPoints;
  else if (input.transactionsLast24h >= t.dayCountMediumThreshold) dayPoints = t.dayMediumPoints;
  else if (input.transactionsLast24h >= t.dayCountLowThreshold) dayPoints = t.dayLowPoints;

  const points = clamp(tenMinPoints + dayPoints, 0, max);
  if (points <= 0) return null;

  const parts: string[] = [];
  if (tenMinPoints > 0) {
    parts.push(`${input.transactionsLast10Min} transactions occurred within the last 10 minutes`);
  }
  if (dayPoints > 0) {
    parts.push(`${input.transactionsLast24h} transactions occurred in the last 24 hours`);
  }

  return {
    category: "velocity_risk",
    description: parts.join("; "),
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// 3. Device risk — is this a device we've never seen for this customer?
// ---------------------------------------------------------------------------
export function scoreDeviceRisk(input: RawTransactionInput): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.device;
  const max = CATEGORY_MAX_POINTS.device_risk;

  if (!input.isNewDevice) return null;

  let points: number = t.newDeviceBasePoints;
  let description = "This device has never been used by this customer before";
  if (input.deviceAgeDays <= t.freshDeviceAgeDays) {
    points += t.freshDeviceBonusPoints;
    description += ` and was first registered ${input.deviceAgeDays === 0 ? "today" : `${input.deviceAgeDays} day(s) ago`}`;
  }
  points = clamp(points, 0, max);

  return {
    category: "device_risk",
    description,
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// 4. Location risk — is this a new or inconsistent location?
// ---------------------------------------------------------------------------
export function scoreLocationRisk(input: RawTransactionInput): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.location;
  const max = CATEGORY_MAX_POINTS.location_risk;

  if (!input.isNewLocation) return null;

  let points: number = t.newLocationBasePoints;
  let description = `Transaction location (${input.location}) has not been seen before for this customer`;

  if (input.previousLocation && input.previousLocation !== input.location) {
    points += t.mismatchBonusPoints;
    description += `, and differs from the most recently known location (${input.previousLocation})`;
  }
  points = clamp(points, 0, max);

  return {
    category: "location_risk",
    description,
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// 5. Failed attempt risk — repeated failures right before this transaction
// ---------------------------------------------------------------------------
export function scoreFailedAttemptRisk(input: RawTransactionInput): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.failedAttempts;
  const max = CATEGORY_MAX_POINTS.failed_attempt_risk;

  if (input.failedAttempts <= 0) return null;

  const points = clamp(input.failedAttempts * t.pointsPerAttempt, 0, t.cap);

  return {
    category: "failed_attempt_risk",
    description: `${input.failedAttempts} failed attempt(s) occurred before this transaction went through`,
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// 6. Account risk — brand-new accounts are inherently riskier
// ---------------------------------------------------------------------------
export function scoreAccountRisk(input: RawTransactionInput): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.account;
  const max = CATEGORY_MAX_POINTS.account_risk;

  let points = 0;
  if (input.accountAgeDays <= t.veryNewDays) points = t.veryNewPoints;
  else if (input.accountAgeDays <= t.newDays) points = t.newPoints;
  else if (input.accountAgeDays <= t.recentDays) points = t.recentPoints;
  else if (input.accountAgeDays <= t.establishedDays) points = t.establishedPoints;

  if (points <= 0) return null;
  points = clamp(points, 0, max);

  return {
    category: "account_risk",
    description: `Account is only ${input.accountAgeDays} day(s) old`,
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// 7. Behavioral anomaly — do multiple independent red flags line up at once?
//    This is the "account takeover" style pattern: no single signal is
//    extreme, but several moderate signals together are much more telling.
// ---------------------------------------------------------------------------
export function scoreBehavioralAnomaly(
  input: RawTransactionInput,
  amountRatio: number | null
): RiskFactorResult | null {
  const t = RULE_THRESHOLDS.behavioral;
  const max = CATEGORY_MAX_POINTS.behavioral_anomaly;

  const flags = [
    input.isNewDevice,
    input.isNewLocation,
    input.failedAttempts >= t.failedAttemptsFlagThreshold,
    (amountRatio ?? 0) >= t.highRatioFlagThreshold,
  ];
  const flagCount = flags.filter(Boolean).length;

  let points = 0;
  if (flagCount >= 3) points = t.threeFlagsPoints;
  else if (flagCount === 2) points = t.twoFlagsPoints;

  if (points <= 0) return null;
  points = clamp(points, 0, max);

  return {
    category: "behavioral_anomaly",
    description: `${flagCount} independent risk indicators occurred together (new device, new location, failed attempts, and/or amount spike), a pattern consistent with account takeover`,
    impact: points,
    severity: severityFor(points, max),
  };
}

// ---------------------------------------------------------------------------
// Orchestrator for this file: run every rule, collect factors + breakdown
// ---------------------------------------------------------------------------
export interface RuleEngineResult {
  score: number;
  breakdown: RuleScoreBreakdown;
  factors: RiskFactorResult[];
}

export function runRuleEngine(input: RawTransactionInput): RuleEngineResult {
  const amountRatio =
    input.historicalAvgAmount > 0 ? input.amount / input.historicalAvgAmount : null;

  const results = [
    scoreAmountAnomaly(input),
    scoreVelocityRisk(input),
    scoreDeviceRisk(input),
    scoreLocationRisk(input),
    scoreFailedAttemptRisk(input),
    scoreAccountRisk(input),
    scoreBehavioralAnomaly(input, amountRatio),
  ];

  const factors = results.filter((r): r is RiskFactorResult => r !== null);

  const breakdown: RuleScoreBreakdown = {
    amount_anomaly: results[0]?.impact ?? 0,
    velocity_risk: results[1]?.impact ?? 0,
    device_risk: results[2]?.impact ?? 0,
    location_risk: results[3]?.impact ?? 0,
    failed_attempt_risk: results[4]?.impact ?? 0,
    account_risk: results[5]?.impact ?? 0,
    behavioral_anomaly: results[6]?.impact ?? 0,
  };

  const rawScore = Object.values(breakdown).reduce((sum, v) => sum + v, 0);
  const score = clamp(Math.round(rawScore), 0, 100);

  // Highest-impact factors first, so the UI can show "top risk factors" directly.
  factors.sort((a, b) => b.impact - a.impact);

  return { score, breakdown, factors };
}
